/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import React from 'react'


export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/evB4ODDbJpWeqRD2/scene.splinecode')
  const myMesh = React.useRef();

  useFrame(() => {
      myMesh.current.rotation.y += 0.007; 
  })

  return (
    <>
      <color attach="background" args={['#696969']} />
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={0.5}
          far={100000}
          near={-100000}
          up={[0, 1, 0]}
          position={[-26.34, 49.13, 386.63]}
          rotation={[-0.38, -0.17, -0.06]}
        />
        <directionalLight
          name="Directional Light 2"
          castShadow
          intensity={1}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[-698.65, -332.93, 53]}
          rotation={[0, 0, 0.03]}
        />
        <group name="Group" position={[96.75, 124.29, -196.46]}>
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials['Sphere 2 Material']}
            castShadow
            receiveShadow
            position={[147.79, 18.11, 133.94]}
            rotation={[0.17, 0, 0]}
            scale={1}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Sphere Material']}
            castShadow
            receiveShadow
            position={[-220.31, 0.52, -167.17]}
          />
          <mesh
            ref={myMesh}
            name="bust-of-medusa-at-the-musei-capitolini-rome-1"
            geometry={nodes['bust-of-medusa-at-the-musei-capitolini-rome-1'].geometry}
            material={nodes['bust-of-medusa-at-the-musei-capitolini-rome-1'].material}
            castShadow
            receiveShadow
            position={[-88.89, -364.51, 172.4]}
            scale={5}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[241.56, 352.93, 553]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.14} />
      </group>
    </>
  )
}

